#!/usr/bin/env sh
set -e

pnpm exec biome check .
cargo fmt --all --manifest-path backend/Cargo.toml -- --check
cargo clippy --manifest-path backend/Cargo.toml --all-targets -- -D warnings
cargo test --manifest-path backend/Cargo.toml
